### create new mission
# @prompt mission_name Mission Name
# @prompt description Mission Description
POST {{base_url}}/mission-management
Content-Type: application/json
Authorization: Bearer {{menta_token}}


{
    "name": "{{mission_name}}",
    "description":"{{description}}"
}


### update mission
# @prompt mission_id Mission ID
# @prompt mission_name Mission Name
# @prompt description Mission Description
PATCH {{base_url}}/mission-management/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


{
    "name": "{{mission_name}}",
    "description": "{{description}}"
}


### remove mission
# @prompt mission_id Mission ID
DELETE {{base_url}}/mission-management/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


### set mission to in-progress
# @prompt mission_id Mission ID to Set In-Progress
PATCH  {{base_url}}/mission/in-progress/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


### set mission to completed
# @prompt mission_id Mission ID to Set Completed
PATCH  {{base_url}}/mission/to-completed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}


### set mission to failed
# @prompt mission_id Mission ID to Set Failed
PATCH  {{base_url}}/mission/to-failed/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta_token}}